/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class space_kscience_kmath_noa_JNoa */

#ifndef _Included_space_kscience_kmath_noa_JNoa
#define _Included_space_kscience_kmath_noa_JNoa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     space_kscience_kmath_noa_JNoa
 * Method:    testException
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_space_kscience_kmath_noa_JNoa_testException
  (JNIEnv *, jclass, jint);

/*
 * Class:     space_kscience_kmath_noa_JNoa
 * Method:    cudaIsAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_space_kscience_kmath_noa_JNoa_cudaIsAvailable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
