/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kscience_kmath_torch_JTorch */

#ifndef _Included_kscience_kmath_torch_JTorch
#define _Included_kscience_kmath_torch_JTorch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kscience_kmath_torch_JTorch
 * Method:    getNumThreads
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kscience_kmath_torch_JTorch_getNumThreads
  (JNIEnv *, jclass);

/*
 * Class:     kscience_kmath_torch_JTorch
 * Method:    setNumThreads
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_kscience_kmath_torch_JTorch_setNumThreads
  (JNIEnv *, jclass, jint);

/*
 * Class:     kscience_kmath_torch_JTorch
 * Method:    createTensor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_kscience_kmath_torch_JTorch_createTensor
  (JNIEnv *, jclass);

/*
 * Class:     kscience_kmath_torch_JTorch
 * Method:    printTensor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kscience_kmath_torch_JTorch_printTensor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kscience_kmath_torch_JTorch
 * Method:    disposeTensor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kscience_kmath_torch_JTorch_disposeTensor
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
